/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.webflux)
    api(libs.org.springframework.boot.spring.boot.starter.data.elasticsearch)
    api(project(":common"))
    compileOnly(libs.org.projectlombok.lombok)
}

description = "elastic"
