/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.eureka.client)
    api(libs.org.springframework.boot.spring.boot.starter.webflux)
    api(libs.org.rocksdb.rocksdbjni)
    api(libs.com.fasterxml.jackson.module.jackson.module.kotlin)
    api(libs.io.projectreactor.kotlin.reactor.kotlin.myextensions)
    api(libs.org.jetbrains.kotlin.kotlin.reflect)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.reactor)
    api(libs.io.projectreactor.kafka.reactor.kafka.x1)
    api(libs.org.springframework.kafka.spring.kafka)
    api(libs.io.confluent.kafka.avro.serializer)
    api(project(":elastic"))
    api(project(":kafka-model"))
    api(libs.org.springframework.cloud.spring.cloud.starter.zipkin)
    api(libs.org.springframework.cloud.spring.cloud.starter.sleuth)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.io.micrometer.micrometer.registry.prometheus)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.io.projectreactor.reactor.test)
    testImplementation(libs.org.springframework.kafka.spring.kafka.test)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "kafka-to-elastic-service"
