/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.kafka.spring.kafka)
    api(libs.io.confluent.kafka.avro.serializer)
    api(libs.javax.annotation.javax.annotation.api)
    api(project(":kafka"))
    api(project(":common"))
    compileOnly(libs.org.projectlombok.lombok)
}

description = "kafka-producer"
