/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.kafka.spring.kafka)
    api(libs.org.apache.avro.avro)
    api(project(":common"))
    compileOnly(libs.org.projectlombok.lombok)
}

description = "kafka-consumer"
