/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":rabbitmq"))
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.eureka.client)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.boot.spring.boot.starter.data.mongodb)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.org.springframework.boot.spring.boot.starter.websocket)
    api(libs.org.springframework.spring.messaging)
    api(libs.org.springframework.security.spring.security.messaging)
    api(libs.org.springframework.session.spring.session.data.redis)
    api(libs.org.springframework.boot.spring.boot.starter.data.redis)
    api(libs.javax.xml.bind.jaxb.api)
    api(libs.javax.ws.rs.javax.ws.rs.api)
    api(libs.javax.xml.parsers.jaxp.api)
    api(libs.net.minidev.json.smart)
    api(libs.org.springframework.boot.spring.boot.starter.amqp)
    api(libs.io.jsonwebtoken.jjwt.api)
    api(project(":common"))
    api(libs.org.springframework.spring.test)
    api(libs.org.springframework.cloud.spring.cloud.starter.zipkin)
    api(libs.org.springframework.cloud.spring.cloud.starter.sleuth)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.io.micrometer.micrometer.registry.prometheus)
    runtimeOnly(libs.io.jsonwebtoken.jjwt.impl)
    runtimeOnly(libs.io.jsonwebtoken.jjwt.jackson)
    testImplementation(libs.org.mockito.mockito.inline)
    testImplementation(libs.de.flapdoodle.embed.de.flapdoodle.embed.mongo)
    testImplementation(libs.org.springframework.amqp.spring.rabbit.test)
    testImplementation(libs.it.ozimov.embedded.redis)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.security.spring.security.test)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "chat-service"
