/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.amqp)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.eureka.client)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.javax.xml.bind.jaxb.api)
    api(libs.javax.ws.rs.javax.ws.rs.api)
    api(libs.javax.xml.parsers.jaxp.api)
    api(libs.io.jsonwebtoken.jjwt.api)
    api(project(":common"))
    api(project(":rabbitmq"))
    api(libs.org.springframework.cloud.spring.cloud.starter.zipkin)
    api(libs.org.springframework.cloud.spring.cloud.starter.sleuth)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.io.micrometer.micrometer.registry.prometheus)
    runtimeOnly(libs.io.jsonwebtoken.jjwt.impl)
    runtimeOnly(libs.io.jsonwebtoken.jjwt.jackson)
    testImplementation(libs.org.springframework.amqp.spring.rabbit.test)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "auth-service"
