/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.flywaydb.flyway.core)
    api(libs.org.postgresql.postgresql)
}

description = "notification-db"
