/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.eureka.client)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.boot.spring.boot.starter.webflux)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.org.springframework.data.spring.data.commons)
    api(libs.org.springframework.boot.spring.boot.starter.data.elasticsearch)
    api(project(":elastic"))
    api(libs.org.springframework.cloud.spring.cloud.starter.zipkin)
    api(libs.org.springframework.cloud.spring.cloud.starter.sleuth)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.io.micrometer.micrometer.registry.prometheus)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(libs.io.projectreactor.reactor.test)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "search-service"
